#+TITLE: Spacemacs configuration
#+AUTHOR: Arnav Sharma
#+BABEL: :cache yes
#+PROPERTY: header-args :tangle yes
#+OPTIONS: toc:2
* What is this?
# This is my spacemacs literate config. It is highly individualized. The file is tangled into =.spacemacs= at runtime using =org-babel-load-file=.
* Table of Contents                                                     :TOC:
- [[#what-is-this][What is this?]]
- [[#installation][Installation]]
  - [[#tools][Tools]]
  - [[#go-related-installations][Go Related Installations]]
  - [[#dotspacemacs][Dotspacemacs]]
- [[#spacemacs-centric-config][Spacemacs centric config]]
  - [[#layers][Layers]]
  - [[#styles-and-other-config][Styles and other config]]
- [[#user-config][User Config]]
  - [[#generic-emacs-config][Generic emacs config]]
  - [[#json-mode][JSON Mode]]
  - [[#eshell][Eshell]]
  - [[#snipe][Snipe]]
  - [[#flycheck][Flycheck]]
  - [[#counsel][Counsel]]
  - [[#ivy-config][Ivy config]]
  - [[#alert-config][Alert config]]
  - [[#company-mode][Company mode]]
  - [[#evil-goggles][Evil goggles]]
  - [[#doom-theme-configuration][Doom theme configuration]]
  - [[#python-mode][Python mode]]
  - [[#go-mode][Go mode]]
  - [[#projectile][Projectile]]
  - [[#lsp-configuration][LSP configuration]]
  - [[#file-mode-configurations][File mode configurations]]
  - [[#org-mode][Org mode]]
    - [[#org-brain][Org brain]]
    - [[#babel-settings][Babel settings]]
    - [[#custom-functions][Custom functions]]
    - [[#column-view][Column view]]
    - [[#clocking][Clocking]]
    - [[#generic][Generic]]
    - [[#export][Export]]
    - [[#gtd][GTD]]
  - [[#git-settings][Git settings]]
  - [[#shell-settings][Shell settings]]
  - [[#pdf-settings][PDF settings]]
  - [[#autosave-go-and-emacs-buffer][Autosave go and emacs buffer]]
  - [[#tramp-mode][Tramp mode]]
  - [[#avy][Avy]]
  - [[#helpful][Helpful]]
  - [[#midnight][Midnight]]
- [[#finish-loading][Finish loading]]

* Installation
** Tools
#+BEGIN_SRC sh :tangle no
  brew install ripgrep
#+END_SRC
** Go Related Installations
#+BEGIN_SRC sh :tangle no
  go get -u -v github.com/mdempsky/gocode
  go get -u -v github.com/rogpeppe/godef
  go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  go get -u -v github.com/fatih/gomodifytags
  go get -u -v github.com/godoctor/godoctor
  go install github.com/godoctor/godoctor
  go get -u -v golang.org/x/tools/cmd/guru
  go get -u -v golang.org/x/tools/cmd/gorename
  go get -u -v github.com/zmb3/gogetdoc
  go get -u -v github.com/cweill/gotests/...
  go get -u github.com/haya14busa/gopkgs/cmd/gopkgs
  go get -u -v github.com/davidrjenni/reftools/cmd/fillstruct
  go get -u github.com/josharian/impl
  go get -u github.com/jstemmer/gotags
  go get golang.org/x/tools/cmd/goimports
#+END_SRC
** Dotspacemacs
Add this inside dotspacemacs to the file going, assuming the repo is checked out in the home folder
#+BEGIN_SRC emacs-lisp :tangle no
   (org-babel-load-file "~/dotfiles/spacemacs.org")
#+END_SRC
* Spacemacs centric config
** Layers
#+BEGIN_SRC emacs-lisp :tangle no

  (defun dotspacemacs/layers ()
    (setq-default
     dotspacemacs-distribution 'spacemacs
     dotspacemacs-configuration-layer-path '()

     dotspacemacs-configuration-layers
     '(javascript
       html
       csv
       auto-completion
       better-defaults
       emacs-lisp
       evil-commentary
       python
       ipython-notebook
       ivy
       go
       git
       pdf
       markdown
       evil-commentary
       finance
       org
       yaml
       shell
       syntax-checking
       my-spotify
       latex
       treemacs
       chrome
       docker
       )

     dotspacemacs-additional-packages '(fish-completion
                                        thrift
                                        ob-go
                                        org-gcal
                                        real-auto-save
                                        org-cliplink
                                        doom-themes
                                        go-direx
                                        org-autolist
                                        )

     dotspacemacs-excluded-packages '(org-projectile
                                      )
     dotspacemacs-delete-orphan-packages t
     ))
#+END_SRC

#+RESULTS:
: dotspacemacs/layers

** Styles and other config
#+BEGIN_SRC emacs-lisp :tangle no
  (defun dotspacemacs/init ()
    "Initialization function.
  This function is called at the very startup of Spacemacs initialization
  before layers configuration.
  You should not put any user code in there besides modifying the variable
  values."
    (setq-default
     dotspacemacs-elpa-https t
     dotspacemacs-elpa-timeout 5
     dotspacemacs-check-for-update t
     dotspacemacs-editing-style 'vim
     dotspacemacs-verbose-loading t
     dotspacemacs-startup-banner 'official
     dotspacemacs-startup-lists '(recents projects)
     dotspacemacs-startup-recent-list-size 5
     dotspacemacs-scratch-mode 'text-mode
     dotspacemacs-themes '(doom-vibrant
                           zenburn
                           gruvbox-dark-soft
                           spacemacs-light
                           moe-dark
                           tsdh-dark
                           solarized-dark)
     dotspacemacs-colorize-cursor-according-to-state t
     dotspacemacs-default-font '("Source Code Pro"
                                 :size 12
                                 :weight normal
                                 :width normal
                                 :powerline-offset 2)
     dotspacemacs-leader-key "SPC"
     dotspacemacs-emacs-leader-key "M-m"
     dotspacemacs-major-mode-emacs-leader-key "C-M-m"
     dotspacemacs-distinguish-gui-tab t
     dotspacemacs-command-key ":"
     dotspacemacs-remap-Y-to-y$ t
     dotspacemacs-default-layout-name "Default"
     dotspacemacs-display-default-layout t
     dotspacemacs-auto-resume-layouts nil
     dotspacemacs-auto-save-file-location 'cache
     dotspacemacs-max-rollback-slots 5
     ;; use ivy anyway - does not matter
     dotspacemacs-use-ido nil
     dotspacemacs-helm-resize nil
     dotspacemacs-helm-no-header t
     dotspacemacs-helm-position 'bottom
     dotspacemacs-enable-paste-micro-state t
     ;; use a higher which key delay to make emacs do less
     ;; it anyway does enough
     dotspacemacs-which-key-delay 0.6
     dotspacemacs-which-key-position 'bottom
     dotspacemacs-loading-progress-bar t
     dotspacemacs-fullscreen-at-startup t
     dotspacemacs-fullscreen-use-non-native nil
     dotspacemacs-maximized-at-startup nil
     dotspacemacs-active-transparency 90
     dotspacemacs-inactive-transparency 90
     dotspacemacs-mode-line-unicode-symbols t
     dotspacemacs-smooth-scrolling t
     ;; no other form of line numbering is worth it
     dotspacemacs-line-numbers 'relative
     dotspacemacs-smartparens-strict-mode nil
     dotspacemacs-highlight-delimiters 'all
     dotspacemacs-persistent-server nil
     ;; rg over everything else else
     dotspacemacs-search-tools '("rg" "ag" "pt" "ack" "grep")
     dotspacemacs-default-package-repository nil
     ;; delete trailing linespace
     dotspacemacs-whitespace-cleanup 'trailing

     ))
#+END_SRC
* User Config
** Generic emacs config

Remap ~SPC-w-w~ to ~ace-window~ instead of ~other-window~
#+BEGIN_SRC emacs-lisp
    (spacemacs/set-leader-keys
      "ww" 'ace-window
      "wW" 'other-window
      )

  (use-package ace-window
  :defer t
  :config
      (set-face-attribute
       'aw-leading-char-face nil
       :foreground "gray"
       :weight 'bold
       :height 2.0)
      (set-face-attribute
       'aw-mode-line-face nil
      :inherit 'mode-line-buffer-id
       :foreground "lawn green"))
#+END_SRC

#+RESULTS:

Aggressive indent
#+BEGIN_SRC emacs-lisp
  (use-package aggressive-indent
    :defer t
    :config
    (setq-default aggressive-indent-comments-too t)
    (add-hook 'go-mode-hook #'aggressive-indent-mode)
    (add-hook 'emacs-lisp-mode-hook #'aggressive-indent-mode)
    (add-hook 'lisp-mode-hook #'aggressive-indent-mode)
    )
#+END_SRC


TLDR for documentation
#+BEGIN_SRC emacs-lisp
(use-package tldr
:defer t)
#+END_SRC

Dired Hydra taken from ([[https://github.com/abo-abo/hydra/wiki/Dired][source]])
#+BEGIN_SRC emacs-lisp
  (defhydra hydra-dired (:hint nil :color pink)
    "
  _+_ mkdir          _v_iew           _m_ark             _(_ details        _i_nsert-subdir    wdired
  _C_opy             _O_ view other   _U_nmark all       _)_ omit-mode      _$_ hide-subdir    C-x C-q : edit
  _D_elete           _o_pen other     _u_nmark           _l_ redisplay      _w_ kill-subdir    C-c C-c : commit
  _R_ename           _M_ chmod        _t_oggle           _g_ revert buf     _e_ ediff          C-c ESC : abort
  _Y_ rel symlink    _G_ chgrp        _E_xtension mark   _s_ort             _=_ pdiff
  _S_ymlink          _h_ up dir       _F_ind marked      _._ toggle hydra   \\ flyspell
  _r_sync            ^ ^              ^ ^                ^ ^                _?_ summary
  _z_ compress-file  _A_ find regexp
  _Z_ compress       _Q_ repl regexp

  T - tag prefix
  "
    ("\\" dired-do-ispell)
    ("(" dired-hide-details-mode)
    (")" dired-omit-mode)
    ("+" dired-create-directory)
    ("=" diredp-ediff)         ;; smart diff
    ("?" dired-summary)
    ("$" diredp-hide-subdir-nomove)
    ("A" dired-do-find-regexp)
    ("C" dired-do-copy)        ;; Copy all marked files
    ("D" dired-do-delete)
    ("E" dired-mark-extension)
    ("e" dired-ediff-files)
    ("F" dired-do-find-marked-files)
    ("G" dired-do-chgrp)
    ("g" revert-buffer)        ;; read all directories again (refresh)
    ("i" dired-maybe-insert-subdir)
    ("l" dired-do-redisplay)   ;; relist the marked or singel directory
    ("M" dired-do-chmod)
    ("m" dired-mark)
    ("O" dired-display-file)
    ("o" dired-find-file-other-window)
    ("Q" dired-do-find-regexp-and-replace)
    ("R" dired-do-rename)
    ("r" dired-do-rsynch)
    ("S" dired-do-symlink)
    ("s" dired-sort-toggle-or-edit)
    ("t" dired-toggle-marks)
    ("U" dired-unmark-all-marks)
    ("u" dired-unmark)
    ("v" dired-view-file)      ;; q to exit, s to search, = gets line #
    ("w" dired-kill-subdir)
    ("Y" dired-do-relsymlink)
    ("z" diredp-compress-this-file)
    ("Z" dired-do-compress)
  ("h" dired-up-directory)
    ("q" nil)
    ("." nil :color blue))

  (define-key dired-mode-map "." 'hydra-dired/body)
#+END_SRC

#+RESULTS:
: hydra-dired/body

Set my email
#+BEGIN_SRC emacs-lisp
 (setq user-mail-address "arnavsharma93@gmail.com")
#+END_SRC
save on =s= in normal mode
#+BEGIN_SRC emacs-lisp
  (define-key evil-normal-state-map (kbd "s") 'save-buffer)
#+END_SRC

Don't move cursor back on exiting insert state
#+BEGIN_SRC emacs-lisp
  (setq evil-move-cursor-back nil)
#+END_SRC

GC settings
#+BEGIN_SRC emacs-lisp
 (setq garbage-collection-messages t)
 (setq large-file-warning-threshold 100000000)

#+END_SRC

Reload and find my dotspacemacs configuration
#+BEGIN_SRC emacs-lisp
     (defun my-reload-config ()
       (interactive)
       (with-eval-after-load 'org
         (org-babel-load-file "~/dotfiles/spacemacs.org"))
     )

  (defun my-find-dotfile ()
    "Edit the `dotfile', in the current window."
    (interactive)
    (find-file-existing "~/dotfiles/spacemacs.org"))

    (spacemacs/set-leader-keys
      "feM" 'my-reload-config
      "fem" 'my-find-dotfile
      )

#+END_SRC

** JSON Mode
#+BEGIN_SRC emacs-lisp
  (spacemacs/set-leader-keys-for-major-mode 'json-mode "=" 'json-mode-beautify)
#+END_SRC

#+RESULTS:

** Eshell
[[https://gitlab.com/ambrevar/emacs-fish-completion][Fish like completion]] to help with completion in eshell
#+BEGIN_SRC emacs-lisp
  (use-package fish-completion
    :defer t
    :config
    (global-fish-completion-mode)
    )
  (setq shell-default-shell 'eshell)

  #+END_SRC


Aliases
#+BEGIN_SRC emacs-lisp
  (add-hook 'eshell-mode-hook (lambda ()
      (eshell/alias "fa" "counsel-projectile-find-file $1")
      (eshell/alias "ff" "counsel-find-file $1")
      (eshell/alias "ll" "ls -l $*")
      (eshell/alias "w" "ace-window $1")
      (eshell/alias "q" "delete-window")
      (eshell/alias "d" "dired $1")
      (eshell/alias "s" "magit-status")
      (eshell/alias "m" "spacemacs/toggle-maximize-buffer")
      ))
#+END_SRC

#+RESULTS:
| (lambda nil (eshell/alias fa counsel-projectile-find-file $1) (eshell/alias ff counsel-find-file $1) (eshell/alias ll ls -l $*) (eshell/alias w ace-window $1) (eshell/alias q delete-window) (eshell/alias d dired $1) (eshell/alias s magit-status) (eshell/alias m spacemacs/toggle-maximize-buffer)) | (lambda nil (eshell/alias fa counsel-projectile-find-file $1) (eshell/alias ff counsel-find-file $1) (eshell/alias ll ls -l $*) (eshell/alias w ace-window $1) (eshell/alias q delete-window) (eshell/alias d dired $1) (eshell/alias s magit-status)) | (lambda nil (eshell/alias fa counsel-projectile-find-file $1) (eshell/alias ff counsel-find-file $1) (eshell/alias ll ls -l $*) (eshell/alias d dired $1) (eshell/alias s magit-status)) | with-editor-export-editor | (lambda nil (add-to-list (quote eshell-visual-commands) ssh) (add-to-list (quote eshell-visual-commands) tail) (add-to-list (quote eshell-visual-commands) htop)) | tramp-eshell-directory-change | spacemacs/disable-vi-tilde-fringe | spacemacs/force-yasnippet-off | spacemacs/init-eshell-xterm-color | spacemacs//eshell-switch-company-frontend | spacemacs/disable-hl-line-mode | spacemacs//init-eshell | eldoc-mode | spacemacs//init-company-eshell-mode | company-mode |


Some configuration copied from [[https://github.com/howardabrams/dot-files/blob/master/emacs-eshell.org][here]]
#+BEGIN_SRC emacs-lisp
  (setq ;; eshell-buffer-shorthand t ...  Can't see Bug#19391
   eshell-scroll-to-bottom-on-input 'all
   eshell-error-if-no-glob t
   eshell-history-size 50000
   eshell-hist-ignoredups t
   eshell-save-history-on-exit t
   eshell-prefer-lisp-functions nil
   eshell-destroy-buffer-when-process-dies t)
  (add-hook 'eshell-mode-hook
            (lambda ()
              (add-to-list 'eshell-visual-commands "ssh")
              (add-to-list 'eshell-visual-commands "tail")
              (add-to-list 'eshell-visual-commands "htop")))
#+END_SRC

Enable Plan9 like smart shell ([[https://www.masteringemacs.org/article/complete-guide-mastering-eshell][source]])
#+BEGIN_SRC emacs-lisp
(setq shell-enable-smart-eshell nil)
#+END_SRC

#+RESULTS:

Clear on ~leader-l~
#+BEGIN_SRC emacs-lisp
   (defun eshell-clear ()
     "Clear the eshell buffer."
     (interactive)
     (let ((inhibit-read-only t))
       (erase-buffer)
       (eshell-send-input)))

  (spacemacs/set-leader-keys-for-major-mode 'eshell-mode "l" 'eshell-clear)
#+END_SRC

Get history on ~leader-h~
#+BEGIN_SRC emacs-lisp
  (spacemacs/set-leader-keys-for-major-mode 'eshell-mode "h" 'counsel-esh-history)
#+END_SRC

Overwriting spacemacs eshell popup as it does not remember history ([[https://github.com/syl20bnr/spacemacs/issues/8538][issue]], [[https://github.com/howardabrams/dot-files/blob/master/emacs-eshell.org][source]])
#+BEGIN_SRC emacs-lisp
  ;; create a new eshell
  (defun eshell-new (name)

    ;; if current buffer is not of eshell
    ;; create a new window in the bottom third
    ;; TODO: fix window sizes when more than one vertical split is present

    (if (not (string= (print major-mode) "eshell-mode"))
        (progn
          (split-window-below (- (/ (window-total-height) 3)))
          (windmove-down)

          ))

    ;; if buffer name not available - create a new buffer, else switch
    (setq shellname (concat "*eshell: " name "*"))


    ;; if name is already eshell:something - don't append eshell again
    (when (string-match "eshell:" name)
      (setq shellname name))

    (if (not (get-buffer shellname))
        (progn
          (eshell "new")
          (rename-buffer  shellname))
      (switch-to-buffer shellname))
    )
#+END_SRC

#+RESULTS:
: eshell-new


Call ivy to show eshell buffers - open one if buffer does not exist. Bind to ~SPC-'~
#+BEGIN_SRC emacs-lisp

  (defun ivy-eshell-new ()
    (interactive)
    ;; find all open buffers of eshell
    (ivy-read "Eshell Buffers:" (mapcar #'buffer-name
                                        (cl-remove-if-not
                                         (lambda (buf)
                                           (with-current-buffer buf
                                             (eq major-mode 'eshell-mode)))
                                         (buffer-list))
                                        )
              :action '(1
                        ("s" eshell-new "switch to buffer"))
              ))
  (spacemacs/set-leader-keys
    "'" 'ivy-eshell-new
    "p'" 'projectile-run-eshell
    )
#+END_SRC

#+RESULTS:


Eshell quit on ~leader-q~ in normal mode
#+BEGIN_SRC emacs-lisp
  (defun exit-eshell-and-delete-window ()
    (interactive)
    (eshell-life-is-too-much)
    (delete-window))

  (defun delete-eshell-window ()
    (interactive)
    (delete-window))

  (spacemacs/set-leader-keys-for-major-mode 'eshell-mode "Q" 'exit-eshell-and-delete-window)
  (spacemacs/set-leader-keys-for-major-mode 'eshell-mode "q" 'delete-eshell-window)
#+END_SRC


** Snipe
[[https://github.com/hlissner/evil-snipe][Evil Snipe]] to supplement avy to move quickly in a line.
#+BEGIN_SRC emacs-lisp

  (use-package evil-snipe
    ;; load on startup
    :ensure t

    :init
    (setq evil-snipe-scope 'line ;; set scope to line
          evil-snipe-enable-highlight t ;; show highlight
          evil-snipe-enable-incremental-highlight t ;; show incremental highlight
          evil-snipe-auto-disable-substitute t ;; needed to make snipe run
          evil-snipe-show-prompt t ;; show 1,2 in the mode line below
          evil-snipe-repeat-keys t ;; multiple presses of f/t takes you forward
          evil-snipe-smart-case t) ;; make snipe handle smart cases
    :config
    ;; enable snipe mode
    (evil-snipe-mode 1)

    ;; modify spacemacs modeline
    (spacemacs|hide-lighter evil-snipe-local-mode)
    ;; override evil f and set everywhere
    (evil-snipe-def 2 'inclusive "f" "F")
    (evil-define-key '(normal motion operator visual) evil-snipe-local-mode-map
      "f" 'evil-snipe-f
      "F" 'evil-snipe-F)
    ;; override evil t and set everywhere
    (evil-snipe-def 1 'exclusive "t" "T")
    (evil-define-key '(normal motion operator visual) evil-snipe-local-mode-map
      "t" 'evil-snipe-t
      "T" 'evil-snipe-T)
    ;; unmap default keybindings
    (evil-define-key '(normal motion) evil-snipe-local-mode-map
      "s" nil
      "S" nil)
    (evil-define-key '(operator) evil-snipe-local-mode-map
      "x" nil
      "X" nil)
    (evil-define-key '(operator) evil-snipe-local-mode-map
      "z" nil
      "Z" nil)
    (push '(?\[ "[[{(]") evil-snipe-aliases)
    (add-hook 'magit-mode-hook 'turn-off-evil-snipe-mode))
#+END_SRC

#+RESULTS:
: t

** Flycheck

Flycheck hangs up in case of huge buffers ([[https://www.reddit.com/r/emacs/comments/7mjyz8/flycheck_syntax_checking_makes_editing_files/][source]]) - found this out when profiled the code
#+BEGIN_SRC emacs-lisp
  (setq flycheck-idle-change-delay 3)
  (setq flycheck-check-syntax-automatically '(save mode-enable))
#+END_SRC

#+RESULTS:
| save | mode-enable |

** Counsel
Counsel Rg to truncate all lines greater than 120 lines ([[https://oremacs.com/2018/03/05/grep-exclude/][source]])
#+BEGIN_SRC emacs-lisp
  (setq counsel-rg-base-command
        "rg -i -M 120 --no-heading --line-number --color never %s ")
#+END_SRC

Ivy occur remapping to ~C-c o~ ([[https://oremacs.com/2015/11/04/ivy-occur/][source]])
#+BEGIN_SRC emacs-lisp
  (define-key ivy-minibuffer-map (kbd "C-c o") 'ivy-occur)
#+END_SRC

Remap ~counsel-projectile-find-file~ to ~pa~ and use ~counsel-git~ as ~pf~ (disabled)
#+BEGIN_SRC emacs-lisp :tangle no
 (spacemacs/set-leader-keys
   "pa" 'counsel-projectile-find-file
   "pf" 'counsel-git
   )

#+END_SRC

#+RESULTS:
** Ivy config
Define ivy builders per function ([[https://emacs.stackexchange.com/questions/36745/enable-ivy-fuzzy-matching-everywhere-except-in-swiper][related source]])
#+BEGIN_SRC emacs-lisp
  (setq ivy-re-builders-alist '((counsel-M-x . ivy--regex-plus)
                                (counsel-describe-function . ivy--regex-plus)
                                (counsel-git . ivy--regex-fuzzy)
                                (counsel-projectile-find-file . ivy--regex-plus)
                                (counsel-find-file . ivy--regex-fuzzy)
                                (counsel-describe-variable . ivy--regex-plus)
                                (spacemacs/counsel-search . spacemacs/ivy--regex-plus)
                                (t . ivy--regex-ignore-order))

   )
#+END_SRC

#+RESULTS:
: ((counsel-M-x . ivy--regex-plus) (counsel-describe-function . ivy--regex-plus) (counsel-git . ivy--regex-fuzzy) (counsel-projectile-find-file . ivy--regex-plus) (counsel-find-file . ivy--regex-fuzzy) (counsel-describe-variable . ivy--regex-plus) (spacemacs/counsel-search . spacemacs/ivy--regex-plus) (t . ivy--regex-ignore-order))

Enable switching to the /special/ buffers & create and set a view ([[http://irreal.org/blog/?p=5355][source]])
#+BEGIN_SRC emacs-lisp
  (setq ivy-use-virtual-buffers t)

  (global-set-key (kbd "C-c v") 'ivy-push-view)
  (global-set-key (kbd "C-c V") 'ivy-pop-view)
  (global-set-key (kbd "C-c s") 'ivy-switch-view)
#+END_SRC
** Alert config
#+BEGIN_SRC emacs-lisp
  (use-package alert
  :defer t
  :config
  (setq alert-default-style 'osx-notifier)
  )
#+END_SRC

#+RESULTS:
: t

** Company mode
Low company idle delay
#+BEGIN_SRC emacs-lisp
  (setq company-idle-delay 0.2)
#+END_SRC

Trigger company completion everytime
#+BEGIN_SRC emacs-lisp
  (setq company-minimum-prefix-length 1)
#+END_SRC

#+RESULTS:
: 1

Trigger company completion only when 3 chars have been typed. Currently disabled.
#+BEGIN_SRC emacs-lisp :tangle no
(spacemacs|disable-company org-mode)
#+END_SRC

#+RESULTS:
| real-auto-save-mode | toc-org-mode | (lambda nil (org-autolist-mode)) | org-indent-mode | ob-ipython-auto-configure-kernels | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-show-block-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | spacemacs/org-setup-evil-surround | spacemacs/load-yasnippet | toc-org-enable | org-download-enable | org-bullets-mode | dotspacemacs//prettify-spacemacs-docs | spacemacs//org-babel-do-load-languages | spacemacs//evil-org-mode | org-eldoc-load |

Don't downcase in case of company autocomplete
#+BEGIN_SRC emacs-lisp
  (setq company-dabbrev-downcase nil)
#+END_SRC

Don't show snippet popups
#+BEGIN_SRC emacs-lisp
 (setq auto-completion-enable-snippets-in-popup nil)
#+END_SRC

Autocomplete sort by word usage
#+BEGIN_SRC emacs-lisp
 (setq auto-completion-enable-sort-by-usage t)
#+END_SRC

Don't do anything on return as prefix length is zero
#+BEGIN_SRC emacs-lisp
 (setq auto-completion-return-key-behavior 'complete)
#+END_SRC

#+RESULTS:
: complete

#+BEGIN_SRC emacs-lisp
(setq company-tooltip-align-annotations t)
#+END_SRC

#+RESULTS:
: t

Autocomplete on ~jk~
#+BEGIN_SRC emacs-lisp
(setq auto-completion-complete-with-key-sequence "jk")
#+END_SRC
** Evil goggles

Evil googles highlight what is yanked etc in evil mode ([[https://github.com/edkolev/evil-goggles][source]])
#+BEGIN_SRC emacs-lisp
  (use-package evil-goggles
    :ensure t
    :config
    (evil-goggles-mode)

    ;; optionally use diff-mode's faces; as a result, deleted text
    ;; will be highlighed with `diff-removed` face which is typically
    ;; some red color (as defined by the color theme)
    ;; other faces such as `diff-added` will be used for other actions
    (evil-goggles-use-diff-faces))

#+END_SRC
** Doom theme configuration
#+BEGIN_SRC emacs-lisp
  (use-package doom-themes
    :config
    ;; Global settings (defaults)
    (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
          doom-themes-enable-italic t) ; if nil, italics is universally disabled
    ;; Enable flashing mode-line on errors
    (doom-themes-visual-bell-config)

    ;; treemacs
    (doom-themes-treemacs-config)

    ;; Corrects (and improves) org-mode's native fontification.
    (doom-themes-org-config)
    )

#+END_SRC
** Python mode

Integrate with python virtualenvwrapper and get it working with eshell ([[https://github.com/porterjamesj/virtualenvwrapper.el][source]])
#+BEGIN_SRC emacs-lisp
  (use-package virtualenvwrapper
    :defer t
    :config
    (venv-initialize-eshell)
    )
#+END_SRC

#+RESULTS:
: t

** Go mode
go-direx to show what all is contained in a go file. remap ~leaderredael~ to =gofmt=.
#+BEGIN_SRC emacs-lisp
  (use-package go-direx
    :defer t
    :config
    )

  (spacemacs/set-leader-keys-for-major-mode 'go-mode "=" 'go-direx-pop-to-buffer)
  (spacemacs/set-leader-keys-for-major-mode 'go-mode "," 'gofmt)
#+END_SRC

#+RESULTS:

#+RESULTS:
| aggressive-indent-mode | real-auto-save-mode | spacemacs//go-set-tab-width | go-eldoc-setup | spacemacs//init-jump-handlers-go-mode | spacemacs//init-company-go-mode | spacemacs//init-company-vars-go-mode | company-mode |

Use much better godoc at point function
#+BEGIN_SRC emacs-lisp
  (setq godoc-at-point-function 'godoc-gogetdoc)
#+END_SRC

Set tab width to 4
#+BEGIN_SRC emacs-lisp
 (setq go-tab-width 4)
#+END_SRC

Run goformat before save
#+BEGIN_SRC emacs-lisp
 (setq go-format-before-save nil)
#+END_SRC

#+RESULTS:

Run goimports on save
#+BEGIN_SRC emacs-lisp
 (setq gofmt-command "goimports")
#+END_SRC

Use gocheck for testing
** Projectile
#+BEGIN_SRC emacs-lisp
(setq go-use-gocheck-for-testing t)
#+END_SRC
  (use-package projectile
    :defer t
    :config
    (add-to-list 'projectile-globally-ignored-directories "vendor" ".gen")
    (setq projectile-sort-order 'recentf)

Use golangci as linter instead of gometaliner
#+BEGIN_SRC emacs-lisp
(setq go-use-golangci-lint t)
#+END_SRC
** LSP configuration
Langauge Server settings. Currently disabled.

Disable lsp ui ([[https://github.com/syl20bnr/spacemacs/issues/11265][source]]) and stop creating lock files ([[https://github.com/emacs-lsp/lsp-mode/issues/378][source]])
#+BEGIN_SRC emacs-lisp :tangle no
  (setq lsp-ui-flycheck-enable nil)
  (setq create-lockfiles nil)
#+END_SRC
** File mode configurations
Enable emacs mode depending on the file format

#+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.avsc\\'" . json-mode))
  (add-to-list 'auto-mode-alist '("\\.csv\\'" . org-mode))
  (add-to-list 'auto-mode-alist '("\\.zsh\\'" . sh-mode))
#+END_SRC
** Org mode
*** Org brain
Org brain config. Disabled for now.
#+BEGIN_SRC emacs-lisp :tangle no
(use-package org-brain :ensure t
  :init
  (setq org-brain-path "~/Dropbox/org/brain")
  ;; For Evil users
  (with-eval-after-load 'evil
    (evil-set-initial-state 'org-brain-visualize-mode 'emacs))
  :config
  (setq org-id-track-globally t)
  (setq org-id-locations-file "~/.emacs.d/.org-id-locations")
  (push '("b" "Brain" plain (function org-brain-goto-end)
          "* %i%?" :empty-lines 1)
        org-capture-templates)
  (setq org-brain-visualize-default-choices 'all)
  (setq org-brain-title-max-length 12))
#+END_SRC

#+RESULTS:
: t

*** Babel settings
Don't ask confirmation while executing in org buffers
#+BEGIN_SRC emacs-lisp
 (setq org-confirm-babel-evaluate nil)
#+END_SRC
*** Custom functions
A nifty function to insert current time in the buffer. Bound to ~leader;~
#+BEGIN_SRC emacs-lisp :tangle no
    (defvar current-time-format "%H:%M"
      "Format of date to insert with `insert-current-time' func.
  Note the weekly scope of the command's precision.")
    (defun insert-current-time ()
      "insert the current time (1-week scope) into the current buffer."
      (interactive)
      (insert (format-time-string current-time-format (current-time)))
      (insert " - ")
      )
  (spacemacs/set-leader-keys-for-major-mode 'org-mode ";" 'insert-current-time)
#+END_SRC
*** Column view
Column view default columns
#+BEGIN_SRC emacs-lisp :tangle no
 (setq org-agenda-overriding-columns-format "%7TODO(Todo) %40ITEM(Task) %TAGS(Tags) %6CLOCKSUM(Actual) %8Effort(Estimate){:}")
#+END_SRC
TODO states
#+BEGIN_SRC emacs-lisp
 (setq org-todo-keywords
       '((sequence "TODO(t)" "INPROGRESS(p/!)" "STOPPED(s/!)" "WAIT(w@/!)" "|" "DONE(d@/!)" "CANCELLED(c@)")))

 (setq org-log-states-order-reversed t)
#+END_SRC
*** Clocking
Clocking configuration
#+BEGIN_SRC emacs-lisp :tangle no
  ;; Resume clocking task when emacs is restarted
  (org-clock-persistence-insinuate)
  ;; Save the running clock and all clock history when exiting Emacs, load it on startup
  (setq org-clock-persist t)
  ;; Resume clocking task on clock-in if the clock is open
  (setq org-clock-in-resume t)
  ;; Do not prompt to resume an active clock, just resume it
  (setq org-clock-persist-query-resume nil)

  ;; Change tasks to whatever when clocking out
  (setq org-clock-out-switch-to-state "STOPPED")
  ;; Change tasks to whatever when clocking in
  (setq org-clock-in-switch-to-state "INPROGRESS")
  ;; Save clock data and state changes and notes in the LOGBOOK drawer
  (setq org-clock-into-drawer t)
  ;; Sometimes I change tasks I'm clocking quickly - this removes clocked tasks
  ;; with 0:00 duration
  (setq org-clock-out-remove-zero-time-clocks t)
  ;; Clock out when moving task to a done state
  (setq org-clock-out-when-done t)
  ;; Enable auto clock resolution for finding open clocks
  ;; commenting out as I don't know what this does
  ;; (setq org-clock-auto-clock-resolution (quote when-no-clock-is-running))
  ;; Include current clocking task in clock reports
  (setq org-clock-report-include-clocking-task t)
  ;; use pretty things for the clocktable
  (setq org-pretty-entities t)

 (spacemacs/toggle-mode-line-org-clock-on)
#+END_SRC
Clocking and other keybindings
#+BEGIN_SRC emacs-lisp :tangle no
 (spacemacs/set-leader-keys-for-major-mode 'org-mode "c" nil)
 (spacemacs/set-leader-keys-for-major-mode 'org-mode "I" nil)
 (spacemacs/set-leader-keys-for-major-mode 'org-mode "O" nil)
 (spacemacs/set-leader-keys-for-major-mode 'org-mode "Q" nil)
 (spacemacs/declare-prefix-for-mode 'org-mode "c" "clock")
 (spacemacs/set-leader-keys-for-major-mode 'org-mode "ck" 'org-clock-cancel)
 (spacemacs/set-leader-keys-for-major-mode 'org-mode "cd" 'org-clock-display)
 (spacemacs/set-leader-keys-for-major-mode 'org-mode "co" 'org-clock-out)
 (spacemacs/set-leader-keys-for-major-mode 'org-mode "cc" 'org-clock-in-last)
 (spacemacs/set-leader-keys-for-major-mode 'org-mode "ci" 'org-clock-in)

 (spacemacs/set-leader-keys-for-major-mode 'org-mode "ic" 'org-cliplink)
 (spacemacs/declare-prefix-for-mode 'org-mode "v" "view")
 (spacemacs/set-leader-keys-for-major-mode 'org-mode "vc" 'org-columns)

 (spacemacs/set-leader-keys-for-major-mode 'org-mode "I" 'org-add-note)
#+END_SRC
*** Generic
Indent in org mode
#+BEGIN_SRC emacs-lisp
 (add-hook 'org-mode-hook 'org-indent-mode)
#+END_SRC

Enable org autolist mode
#+BEGIN_SRC emacs-lisp
 (add-hook 'org-mode-hook (lambda () (org-autolist-mode)))
#+END_SRC

#+RESULTS:
| (lambda nil (org-autolist-mode)) | real-auto-save-mode | toc-org-mode | org-indent-mode | org-clock-load | ob-ipython-auto-configure-kernels | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-show-block-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | spacemacs/org-setup-evil-surround | spacemacs/load-yasnippet | toc-org-enable | org-download-enable | org-bullets-mode | dotspacemacs//prettify-spacemacs-docs | spacemacs//org-babel-do-load-languages | spacemacs//evil-org-mode | org-eldoc-load | spacemacs//init-company-org-mode | company-mode |

Keep super and subscripts as it is
#+BEGIN_SRC emacs-lisp
 (setq org-use-sub-superscripts nil)
#+END_SRC

Don't startup truncated. Currently disabled.
#+BEGIN_SRC emacs-lisp :tangle no
 (setq org-startup-truncated nil)
#+END_SRC
Remap ~C-'~ to nil so that avy can work as expected
#+BEGIN_SRC emacs-lisp
 (define-key org-mode-map (kbd "C-'") nil)
#+END_SRC

Adding [[https://github.com/snosov1/toc-org/blob/master/README.org][toc-org]] to generate toc for github in buffer
#+BEGIN_SRC emacs-lisp
  (use-package toc-org
    :defer t
    :config
    (add-hook 'org-mode-hook 'toc-org-mode)
    (add-to-list 'org-tag-alist '("TOC" . ?T))
    )
#+END_SRC

#+RESULTS:
: t

*** Export
Get org export to pdf working ([[https://emacs.stackexchange.com/questions/20839/exporting-code-blocks-to-pdf-via-latex][source]])
#+BEGIN_SRC emacs-lisp
 (use-package org
   :defer t
   :config
   (progn
     ;; (use-package ox-latex :ensure t)
     (add-to-list 'org-latex-packages-alist '("" "minted"))
     (setq org-latex-listings 'minted)

     (setq org-latex-pdf-process
           '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
             "bibtex %b"
             "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
             "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))

     (setq org-src-fontify-natively t)

     (org-babel-do-load-languages
      'org-babel-load-languages
      '((R . t)
        (latex . t)))
     )
   )
#+END_SRC
*** GTD

Org mode files
#+BEGIN_SRC emacs-lisp
 (defun my-org/open-inbox-file()
   (interactive)
   (find-file "~/Dropbox/org/gtd/inbox.org")
   )

 (defun my-org/open-gtd-file()
   (interactive)
   (find-file "~/Dropbox/org/gtd/gtd.org")
   )

 (spacemacs/set-leader-keys
   "oo" 'org-capture
   "oi" 'my-org/open-inbox-file
   "og" 'my-org/open-gtd-file
   "oa" 'org-agenda
   "oc" 'org-clock-goto
   )

#+END_SRC

Effort configurations
#+BEGIN_SRC emacs-lisp
 (setq org-global-properties
       '(("Effort_ALL" .
          "0:15 0:30 0:45 1:00 2:00 3:00 4:00 5:00 6:00 8:00")))

#+END_SRC

Log changes in drawer
#+BEGIN_SRC emacs-lisp
 (setq org-log-into-drawer t)
#+END_SRC

Org id set and export
#+BEGIN_SRC emacs-lisp
  (setq org-id-link-to-org-use-id t)
  (setq org-export-with-section-numbers nil)

  (add-hook 'org-capture-prepare-finalize-hook 'org-id-get-create)
  (add-hook 'org-capture-after-finalize-hook  'org-id-update-id-locations)

#+END_SRC

Org capture templates
#+BEGIN_SRC emacs-lisp
 (setq org-capture-templates '(("t" "Todo [inbox]" entry
                                (file+headline "~/Dropbox/org/gtd/inbox.org" "Tasks")
                                (file "~/Dropbox/org/templates/todo.orgcaptmpl")
                                :empty-lines 1)
                               ("T" "Tickler" entry
                                (file+headline "~/Dropbox/org/gtd/tickler.org" "Tickler")
                                "* %i%? \n %U" :empty-lines 1)
                               ("i" "Interview"
                                entry
                                (file "~/Dropbox/org/interviews.org")
                                (file "~/Dropbox/org/templates/interview.orgcaptmpl"))
                               ("n" "Note" entry
                                (file+headline "~/Dropbox/org/notes.org" "Notes")
                                "* %i%? %^g\nLogged on %U" :empty-lines 1)
                               ("j" "Journal" entry
                                (file+olp+datetree "~/Dropbox/org/journal.org")
                                "* Logged on %U\n- %?" :empty-lines 1)))
#+END_SRC

Org refiling configuration
#+BEGIN_SRC emacs-lisp
 (setq org-refile-targets '(("~/Dropbox/org/gtd/gtd.org" :maxlevel . 3)
                            ("~/Dropbox/org/gtd/someday.org" :level . 1)
                            ("~/Dropbox/org/gtd/tickler.org" :maxlevel . 2)))
 (setq org-refile-use-outline-path 'file
       org-outline-path-complete-in-steps nil)
 (setq org-refile-allow-creating-parent-nodes 'confirm)

#+END_SRC

List of agenda files
#+BEGIN_SRC emacs-lisp
  (setq org-agenda-files '("~/Dropbox/org/gtd/inbox.org"
                           "~/Dropbox/org/gtd/gtd.org"
                           "~/Dropbox/org/gtd/tickler.org"))

 (setq arnav/org-agenda-someday-view
       `("s" "Someday" todo ""
         ((org-agenda-files '("~/Dropbox/org/gtd/someday.org")))))

 (setq arnav/org-agenda-banker-view
       `("b" "Banker" search "LEVEL=1/Banker"
         ((org-agenda-files '("~/Dropbox/org/gtd/gtd.org")))))

 (setq arnav/org-agenda-inbox-view
       `("i" "Inbox" todo ""
         ((org-agenda-files '("~/Dropbox/org/gtd/inbox.org")))))

 (setq arnav/org-agenda-tickler-view
       `("T" "tickler" todo ""
         ((org-agenda-files '("~/Dropbox/org/gtd/tickler.org")))))

 (setq org-agenda-custom-commands
       `(,arnav/org-agenda-inbox-view
         ,arnav/org-agenda-someday-view
         ,arnav/org-agenda-tickler-view
         ,arnav/org-agenda-banker-view
         ))

#+END_SRC

** Git settings
Set =giteditor= as emacs using =witheditor=
#+BEGIN_SRC emacs-lisp
  (define-key (current-global-map)
    [remap async-shell-command] 'with-editor-async-shell-command)
  (define-key (current-global-map)
    [remap shell-command] 'with-editor-shell-command)
  (add-hook 'eshell-mode-hook 'with-editor-export-editor)
  (add-hook 'term-exec-hook   'with-editor-export-editor)
#+END_SRC

Switch to alernate window when running magit. Not sure what it does. Currently disabled.
#+BEGIN_SRC emacs-lisp :tangle no
  (add-hook 'shell-command-with-editor-mode-hook 'spacemacs/alternate-window)
#+END_SRC

Show branch name before tags
#+BEGIN_SRC emacs-lisp
 (setq magit-log-show-refname-after-summary t)
#+END_SRC

Hydra for resolving merge conflicts ([[https://github.com/alphapapa/unpackaged.el#smerge-mode][source]])
#+BEGIN_SRC emacs-lisp
  (use-package smerge-mode
    :defer t
    :config
    (defhydra unpackaged/smerge-hydra
      (:color pink :hint nil :post (smerge-auto-leave))
      "
  ^Move^       ^Keep^               ^Diff^                 ^Other^
  ^^-----------^^-------------------^^---------------------^^-------
  _n_ext       _b_ase               _<_: upper/base        _C_ombine
  _p_rev       _u_pper              _=_: upper/lower       _r_esolve
  ^^           _l_ower              _>_: base/lower        _k_ill current
  ^^           _a_ll                _R_efine
  ^^           _RET_: current       _E_diff
  "
      ("n" smerge-next)
      ("p" smerge-prev)
      ("b" smerge-keep-base)
      ("u" smerge-keep-upper)
      ("l" smerge-keep-lower)
      ("a" smerge-keep-all)
      ("RET" smerge-keep-current)
      ("\C-m" smerge-keep-current)
      ("<" smerge-diff-base-upper)
      ("=" smerge-diff-upper-lower)
      (">" smerge-diff-base-lower)
      ("R" smerge-refine)
      ("E" smerge-ediff)
      ("C" smerge-combine-with-next)
      ("r" smerge-resolve)
      ("k" smerge-kill-current)
      ("ZZ" (lambda ()
              (interactive)
              (save-buffer)
              (bury-buffer))
       "Save and bury buffer" :color blue)
      ("q" nil "cancel" :color blue))
    :hook (magit-diff-visit-file . (lambda ()
                                     (when smerge-mode
                                       (unpackaged/smerge-hydra/body)))))
#+END_SRC

#+RESULTS:
| lambda | nil | (when smerge-mode (unpackaged/smerge-hydra/body)) |


** Shell settings
Run =zsh= in an inferior shell
#+BEGIN_SRC emacs-lisp
  (setq explicit-shell-file-name "/bin/zsh")
#+END_SRC

Save history of shell-commands run
#+BEGIN_SRC emacs-lisp
  (setq savehist-save-minibuffer-history 1)
  (setq savehist-additional-variables
        '(kill-ring search-ring regexp-search-ring compile-history log-edit-comment-ring)
        savehist-file "~/.emacs.d/savehist")
  (savehist-mode t)
#+END_SRC

Exit async buffer on ~q~
#+BEGIN_SRC emacs-lisp
 (defun maybe-set-quit-key ()
   (when (string= (buffer-name) "*Async Shell Command*")
     (local-set-key (kbd "q") #'quit-window)))

 (add-hook 'shell-mode-hook #'maybe-set-quit-key)
#+END_SRC

SHX package for extra shell niceities
#+BEGIN_SRC emacs-lisp
  (use-package shx
    :defer t
    :config
    (shx-global-mode 1))
#+END_SRC

#+RESULTS:
: t

** PDF settings
Turn off line numbering in pdf view
#+BEGIN_SRC emacs-lisp
 (add-hook 'pdf-view-mode-hook (lambda() (linum-mode -1)))
#+END_SRC

** Autosave go and emacs buffer
Auto save org and go mode buffers after 15 odd minutes
#+BEGIN_SRC emacs-lisp
 (use-package real-auto-save
   :init
   (setq real-auto-save-interval 1800)
   :config
   (add-hook 'org-mode-hook 'real-auto-save-mode)
   (add-hook 'go-mode-hook 'real-auto-save-mode)
   )

#+END_SRC
** Tramp mode
Tramp mode speedups attempts ([[https://www.emacswiki.org/emacs/TrampMode][source]])
#+BEGIN_SRC emacs-lisp
 (setq remote-file-name-inhibit-cache nil)
 (setq tramp-completion-reread-directory-timeout nil)
 (setq vc-ignore-dir-regexp
       (format "\\(%s\\)\\|\\(%s\\)"
               vc-ignore-dir-regexp
               tramp-file-name-regexp))
#+END_SRC

Run to change tramp mode verbosity
#+BEGIN_SRC emacs-lisp :tangle no
 (setq tramp-verbose 3)
#+END_SRC

#+RESULTS:
: 3

Speed up tramp on slow connections ([[https://emacs.stackexchange.com/questions/22306/working-with-tramp-mode-on-slow-connection-emacs-does-network-trip-when-i-start][source]], [[https://emacs.stackexchange.com/questions/24159/tramp-waiting-for-prompts-from-remote-shell][source]])
#+BEGIN_SRC emacs-lisp
  (setq disable-tramp-backups '("su" "sudo"))
  (setq tramp-auto-save-directory "/tmp")
  (setq tramp-ssh-controlmaster-options "")
#+END_SRC

Enviornment variables ([[https://emacs.stackexchange.com/questions/461/configuration-of-eshell-running-programs-from-directories-in-path-env-variable/2106#2106][source]])
#+BEGIN_SRC emacs-lisp
(add-to-list 'tramp-remote-path 'tramp-own-remote-path)
#+END_SRC

#+RESULTS:
| tramp-own-remote-path | tramp-default-remote-path | /bin | /usr/bin | /sbin | /usr/sbin | /usr/local/bin | /usr/local/sbin | /local/bin | /local/freeware/bin | /local/gnu/bin | /usr/freeware/bin | /usr/pkg/bin | /usr/contrib/bin | /opt/bin | /opt/sbin | /opt/local/bin |

Add this to your ~.ssh/config~
#+BEGIN_SRC sh :tangle no
Host *
ControlMaster auto
ControlPath ~/.ssh/sockets/%r@%h-%p
ControlPersist 600
#+END_SRC
** Avy
Set timeout for avy timer
#+BEGIN_SRC emacs-lisp
 (setq avy-timeout-seconds 0.3)
#+END_SRC

#+RESULTS:
: 0.3

Map ~/~ to run avy timer
#+BEGIN_SRC emacs-lisp
  (define-key evil-evilified-state-map (kbd "/") 'avy-goto-char-timer)
  (define-key evil-motion-state-map (kbd "/") 'avy-goto-char-timer)
  (define-key evil-operator-state-map (kbd "/") 'avy-goto-char-timer)
  (define-key evil-normal-state-map (kbd "/") 'avy-goto-char-timer)
#+END_SRC

#+RESULTS:
: avy-goto-char-timer

** Helpful
#+BEGIN_SRC emacs-lisp
  (use-package helpful
    :defer t
    :config
    (push (cons #'helpful-functions #'ivy--regex-plus)
          ivy-re-builders-alist)

    (push (cons #'helpful-variables #'ivy--regex-plus)
          ivy-re-builders-alist)

    )
#+END_SRC

#+RESULTS:
: t

#+BEGIN_SRC emacs-lisp
 (spacemacs/set-leader-keys
   "hdf" 'helpful-callable
   "hdv" 'helpful-variable
   "hdk" 'helpful-key
   "hdd" 'helpful-at-point
   )

#+END_SRC
#+RESULTS:

** Midnight
Remove unused buffers after a certain time

#+BEGIN_SRC emacs-lisp
(use-package midnight
:ensure t)
#+END_SRC

* Finish loading
#+BEGIN_SRC emacs-lisp
  (alert "Successfully loaded: booyeah" :title "Dotspacemacs")
#+END_SRC

#+RESULTS:
Wrong type argument: integer-or-marker-p, nil
(eshell-life-is-too-much)
